//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchangeWpfClient.CurrencyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalanceInfo", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchangeService")]
    [System.SerializableAttribute()]
    public partial class BalanceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] AmountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CurrenciesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Amounts {
            get {
                return this.AmountsField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountsField, value) != true)) {
                    this.AmountsField = value;
                    this.RaisePropertyChanged("Amounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Currencies {
            get {
                return this.CurrenciesField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrenciesField, value) != true)) {
                    this.CurrenciesField = value;
                    this.RaisePropertyChanged("Currencies");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        double GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExchangeCurrency", ReplyAction="http://tempuri.org/IService1/ExchangeCurrencyResponse")]
        double ExchangeCurrency(double amount, string fromCurrency, string toCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExchangeCurrency", ReplyAction="http://tempuri.org/IService1/ExchangeCurrencyResponse")]
        System.Threading.Tasks.Task<double> ExchangeCurrencyAsync(double amount, string fromCurrency, string toCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAvailableCurrencies", ReplyAction="http://tempuri.org/IService1/GetAvailableCurrenciesResponse")]
        string[] GetAvailableCurrencies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAvailableCurrencies", ReplyAction="http://tempuri.org/IService1/GetAvailableCurrenciesResponse")]
        System.Threading.Tasks.Task<string[]> GetAvailableCurrenciesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        bool Register(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        double GetBalance(string username, string currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        System.Threading.Tasks.Task<double> GetBalanceAsync(string username, string currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TopUp", ReplyAction="http://tempuri.org/IService1/TopUpResponse")]
        double TopUp(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TopUp", ReplyAction="http://tempuri.org/IService1/TopUpResponse")]
        System.Threading.Tasks.Task<double> TopUpAsync(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBalances", ReplyAction="http://tempuri.org/IService1/GetAllBalancesResponse")]
        CurrencyExchangeWpfClient.CurrencyService.BalanceInfo GetAllBalances(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBalances", ReplyAction="http://tempuri.org/IService1/GetAllBalancesResponse")]
        System.Threading.Tasks.Task<CurrencyExchangeWpfClient.CurrencyService.BalanceInfo> GetAllBalancesAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        bool BuyCurrency(string username, double amount, string fromCurrency, string toCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        System.Threading.Tasks.Task<bool> BuyCurrencyAsync(string username, double amount, string fromCurrency, string toCurrency);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CurrencyExchangeWpfClient.CurrencyService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CurrencyExchangeWpfClient.CurrencyService.IService1>, CurrencyExchangeWpfClient.CurrencyService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public double GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public double ExchangeCurrency(double amount, string fromCurrency, string toCurrency) {
            return base.Channel.ExchangeCurrency(amount, fromCurrency, toCurrency);
        }
        
        public System.Threading.Tasks.Task<double> ExchangeCurrencyAsync(double amount, string fromCurrency, string toCurrency) {
            return base.Channel.ExchangeCurrencyAsync(amount, fromCurrency, toCurrency);
        }
        
        public string[] GetAvailableCurrencies() {
            return base.Channel.GetAvailableCurrencies();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAvailableCurrenciesAsync() {
            return base.Channel.GetAvailableCurrenciesAsync();
        }
        
        public bool Register(string username, string password) {
            return base.Channel.Register(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password) {
            return base.Channel.RegisterAsync(username, password);
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public double GetBalance(string username, string currency) {
            return base.Channel.GetBalance(username, currency);
        }
        
        public System.Threading.Tasks.Task<double> GetBalanceAsync(string username, string currency) {
            return base.Channel.GetBalanceAsync(username, currency);
        }
        
        public double TopUp(string username, double amount) {
            return base.Channel.TopUp(username, amount);
        }
        
        public System.Threading.Tasks.Task<double> TopUpAsync(string username, double amount) {
            return base.Channel.TopUpAsync(username, amount);
        }
        
        public CurrencyExchangeWpfClient.CurrencyService.BalanceInfo GetAllBalances(string username) {
            return base.Channel.GetAllBalances(username);
        }
        
        public System.Threading.Tasks.Task<CurrencyExchangeWpfClient.CurrencyService.BalanceInfo> GetAllBalancesAsync(string username) {
            return base.Channel.GetAllBalancesAsync(username);
        }
        
        public bool BuyCurrency(string username, double amount, string fromCurrency, string toCurrency) {
            return base.Channel.BuyCurrency(username, amount, fromCurrency, toCurrency);
        }
        
        public System.Threading.Tasks.Task<bool> BuyCurrencyAsync(string username, double amount, string fromCurrency, string toCurrency) {
            return base.Channel.BuyCurrencyAsync(username, amount, fromCurrency, toCurrency);
        }
    }
}
